### ISSUE TITLE
Диаграммы компонентов и последовательностей

### ISSUE THREAD

**Issue by AniSkyWorker** [ivan-uskov/go-labs#2]
- [x] Не совсем понятно, станции будут просто внешними серверами или будут реализовываться как отдельные прокси-сервисы на нашей стороне? Стоит дописать пояснительную записку, что есть что.
- [x] На диаграмме последовательностей принято отрисовывать именно компоненты, т.к. это сущности время жизни которых независимо друг от друга. Weather store - я так полагаю это сущность внутри компонента weatherservice?

**Comment by ivan-uskov** [comment]
Добавил описание, поправил диаграмки
