### ISSUE TITLE
orderservice

### ISSUE THREAD

**Issue by AniSkyWorker** [ivan-uskov/go-labs#3]
- [x] в order.go можно не экспортировать сущности(не писать с большой буквы), т.к. кроме этого пакета они нигде не используются
- [x] в методе orders тоже можно переиспользовать renderJson
- [x] нет логирования длительности запроса

**Comment by ivan-uskov** [comment]
1) ![image](https://user-images.githubusercontent.com/9018385/109690209-2bcc0080-7b97-11eb-9c2e-2d6c0a83319b.png)
Я так понимаю что лучше делать публичными для сериализации в json


2) поправил

3) поправил

**Comment by AniSkyWorker** [comment]
Я имел в виду не поля, а сами сущности. Поля - да, должны быть экспортируемыми, чтобы их пакет json видел. Сущности могут быть не экспортируемыми

**Comment by ivan-uskov** [comment]
Поправил)
